name: Build & Deploy

on:
  push:
    branches: [ "main", upd/events ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v4

      - name: 🧰 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: 📥 Install dependencies for Expo app
        working-directory: ./frontend
        run: npm i
  
      - name: 🏗️ Build Expo web app
        working-directory: ./frontend
        env:
          EXPO_PUBLIC_API_URL: ${{ secrets.EXPO_PUBLIC_API_URL }}
          # REACT_APP_API_BASE_URL: ${{ secrets.APP_URL }}
          # EXPO_PUBLIC_STRIPE_PUBLIC_KEY: ${{ secrets.STRIPE_PUB_KEY }}
        run: |
          echo "Build: EXPO_PUBLIC_API_URL is set to: [$EXPO_PUBLIC_API_URL]"
          # Clean the URL by removing any extra quotes
          export EXPO_PUBLIC_API_URL=$(echo "$EXPO_PUBLIC_API_URL" | sed "s/'//g" | sed 's/"//g')
          echo "Cleaned EXPO_PUBLIC_API_URL: [$EXPO_PUBLIC_API_URL]"
          npm run build:web
  
      - name: 🔐 Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 🚀 Deploy dist folder to VPS
        run: |
          echo "🔍 Deploying dist to ${{ secrets.VPS_HOST }} as ${{ secrets.VPS_USER }}"
          echo "📁 Listing current directory..."
          pwd
          ls -la
          # Navigate into frontend directory where dist is located
          cd ./frontend
          echo "✅ Verifying dist exists..."
          if [ ! -d "dist" ]; then
            echo "❌ dist folder not found! Build may have failed."
            exit 1
          fi
          echo "📂 Creating /root/progressweb/frontend/dist on VPS if it doesn't exist..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "mkdir -p /root/progressweb/frontend"
          echo "📤 Removing old dist directory on VPS..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "rm -rf /root/progressweb/frontend/dist"
          echo "📤 Uploading dist to /root/progressweb/frontend/ ..."
          scp -v -r dist ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/root/progressweb/frontend/
          echo "♻️ Restarting app with PM2..."
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd /root/progressweb
            echo "🔄 Pulling latest changes from git..."
            git pull
            # Assuming your PM2 process serves from the reactapp/dist directory or similar
            # Adjust the PM2 command if your server setup is different
            pm2 restart 11 || pm2 start npm --name "progressweb" -- start
          EOF
          echo "✅ Deploy complete!!"
